spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'dev'
    password: 'example'
